In [ ]:
import pandas as pd
import numpy as np
import glob

:

In [2]:
path = "../data/x4/"
fname = "image_info_220704.csv"

In [3]:
file = pd.read_csv(path+fname)

FileNotFoundError: ignored

In [ ]:
file.keys()

Index(['実験番号id', '撮影日付', 'ラウンド数', '培養開始後経過日数(Day xx)', '撮影方法', '撮影機器名', 'x 倍率',
       '固定の有無', 'フォルダ名', 'Day82 Myf5', 'FLAG'],
      dtype='object')

In [ ]:
file

,実験番号id,撮影日付,ラウンド数,培養開始後経過日数(Day xx),撮影方法,撮影機器名,x 倍率,固定の有無,フォルダ名,Day82 Myf5,FLAG
0,40,2021/03/22,#8,38,phase,KEYence 第四世代,4,無,/Day38/#8/#8_0.5A,9.0,1
1,41,2021/03/22,#8,38,phase,KEYence 第四世代,4,無,/Day38/#8/#8_1A,5.9,1
2,42,2021/03/22,#8,38,phase,KEYence 第四世代,4,無,/Day38/#8/#8_2A,13.0,0
3,43,2021/03/22,#8,38,phase,KEYence 第四世代,4,無,/Day38/#8/#8_0.5B,8.4,1
4,44,2021/03/22,#8,38,phase,KEYence 第四世代,4,無,/Day38/#8/#8_1B,11.6,0
...,...,...,...,...,...,...,...,...,...,...,...
267,71,2021/07/23,#13,14,phase,KEYence 第四世代,4,無,/Day14/#13/#13_0.3-1,17.0,0
268,72,2021/07/23,#13,14,phase,KEYence 第四世代,4,無,/Day14/#13/#13_0.3-2,8.3,1
269,73,2021/07/23,#13,14,phase,KEYence 第四世代,4,無,/Day14/#13/#13_0.5-0.5,4.2,1
270,74,2021/07/23,#13,14,phase,KEYence 第四世代,4,無,/Day14/#13/#13_0.5-1,18.3,0
271,75,2021/07/23,#13,14,phase,KEYence 第四世代,4,無,/Day14/#13/#13_0.5-2,18.5,0

In [ ]:
cols = ["batchno","day","dish","fname","Mean82","FLAG"]
df = pd.DataFrame([],columns=cols)

count = 0
for index, row in file.iterrows():
    #folder = path + "/Day38/"+ row["撮影日付"] + "/" +row["フォルダ名"] + "/"
    folder = path + "/" +row["フォルダ名"] + "/"
    impathlist = glob.glob(folder+"*.tif")
    #print(impathlist)
    for impath in impathlist:
        array = []

        array.append(row["ラウンド数"])
        array.append(row["培養開始後経過日数(Day xx)"])
        array.append(row["フォルダ名"])
        array.append(impath)
        array.append(row["Day82 Myf5"])
        array.append(row["FLAG"])

        df.loc[count] = array

        count = count +1

In [ ]:
df

,batchno,day,dish,fname,Mean82,FLAG
0,#8,38,/Day38/#8/#8_0.5A,../data/x4///Day38/#8/#8_0.5A/1_XY01_00107_CH4...,9.0,1
1,#8,38,/Day38/#8/#8_0.5A,../data/x4///Day38/#8/#8_0.5A/1_XY01_00117_CH4...,9.0,1
2,#8,38,/Day38/#8/#8_0.5A,../data/x4///Day38/#8/#8_0.5A/1_XY01_00121_CH4...,9.0,1
3,#8,38,/Day38/#8/#8_0.5A,../data/x4///Day38/#8/#8_0.5A/1_XY01_00092_CH4...,9.0,1
4,#8,38,/Day38/#8/#8_0.5A,../data/x4///Day38/#8/#8_0.5A/1_XY01_00120_CH4...,9.0,1
...,...,...,...,...,...,...
5707,#13,14,/Day14/#13/#13_0.5-2,../data/x4///Day14/#13/#13_0.5-2/1_XY06_00119_...,18.5,0
5708,#13,14,/Day14/#13/#13_0.5-2,../data/x4///Day14/#13/#13_0.5-2/1_XY06_00134_...,18.5,0
5709,#13,14,/Day14/#13/#13_0.5-2,../data/x4///Day14/#13/#13_0.5-2/1_XY06_00146_...,18.5,0
5710,#13,14,/Day14/#13/#13_0.5-2,../data/x4///Day14/#13/#13_0.5-2/1_XY06_00135_...,18.5,0
5711,#13,14,/Day14/#13/#13_0.5-2,../data/x4///Day14/#13/#13_0.5-2/1_XY06_00147_...,18.5,0

In [ ]:
df.to_csv("../data/imlistD14_38.csv")